SEPOLICY_JOS_PATH := jos/sepolicy

COMMON_JOS_PRIVATE := $(SEPOLICY_JOS_PATH)/common/private
COMMON_JOS_PUBLIC := $(SEPOLICY_JOS_PATH)/common/public

PRODUCT_JOS_PRIVATE := $(SEPOLICY_JOS_PATH)/$(TARGET_PRODUCT)/private
PRODUCT_JOS_PUBLIC := $(SEPOLICY_JOS_PATH)/$(TARGET_PRODUCT)/public

# common sepolicy
BOARD_SEPOLICY_DIRS += $(SEPOLICY_JOS_PATH)/common
# product sepolicy
BOARD_SEPOLICY_DIRS += $(SEPOLICY_JOS_PATH)/$(TARGET_PRODUCT)

SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += \
    $(COMMON_JOS_PRIVATE) \
    $(COMMON_JOS_PUBLIC)

SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS += \
    $(COMMON_JOS_PUBLIC) \
    $(PRODUCT_JOS_PUBLIC)